project:
  type: website
  output-dir: "docs"

website:
  title: "demonstrandom■"
  description: "Random musings"
  site-url: demonstrandom.com
  navbar:
    right:
      - text: About
        href: about.qmd
      - text: Archive
        href: archive.qmd

format:
  html:
    theme: litera