baseURL = "http://example.org/"
languageCode = "en-us"
title = "DemonstRandom∎"
theme = "book"

BookMenuBundle = "/menu"
disqusShortname = "kprocopio"
twitter = "https://twitter.com/DemonstRandom"

[params]
    custom_css = ["css/contact_form.css"]
